#!/bin/bash

langf=$(tput bold && tput setaf 2)
langn=bash
langv=$(bash --version | grep -v "License")

g=$(tput setaf 5)
b=$(tput bold)
reset=$(tput sgr0)

cat << EndOfIntro

${g}glasnt${reset}'s wat-reference for ${langf}${langn}${reset}

We're using: 
${langv}

Try these examples: 

echo 4 + 2
echo \$(4 + 2)
echo \$((4 + 2))

See the ${b}${langn}/README.md${reset} for references, and more information. 
🥊
EndOfIntro
