#!/bin/bash

set -e

LANGUAGE=$1
IMAGE=wat-example-$LANGUAGE


nice_exit(){
    echo "❌ $1"
    if [ "${BASH_SOURCE[0]}" != "${0}" ]
    then
        return # if source filename.sh
    else
        exit 1 # if ./filename.sh
    fi
}

if [ -z "$LANGUAGE" ]; then
    nice_exit "Please specify a language"
fi

if [ ! -d references/$LANGUAGE ]
then
    nice_exit "No example for language '$LANGUAGE'"
fi

DOCKER=$(docker --version)
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]
then
    nice_exit "❌ You don't appear to have docker installed. https://www.docker.com/get-started"
fi

echo "▶️  Start up a $LANGUAGE environment"

docker build -t $IMAGE references/$LANGUAGE 
docker run --rm -it $IMAGE
