#!/bin/bash

langf=$(tput bold && tput setaf 1)
langn="javascript"
langv=$(nodejs --version)

g=$(tput setaf 5)
b=$(tput bold)
reset=$(tput sgr0)

cat << EndOfIntro

${g}glasnt${reset}'s wat-reference for ${langf}${langn}${reset}

We're using: 
${langv}

Try these examples: 

[] + []
[] + {}
{} + []
{} + {}

See the ${b}${langn}/README.md${reset} for references, and more information. 
📜
EndOfIntro
