#!/bin/bash

langf=$(tput bold && tput setaf 3)
langn=python
langv=$(python --version)

g=$(tput setaf 5)
b=$(tput bold)
reset=$(tput sgr0)

cat << EndOfIntro

${g}glasnt${reset}'s wat-reference for ${langf}${langn}${reset}

We're using: 
${langv}

Try these examples: 

a = 257
b = 257
a is b

a = 257; b = 257
a is b

See the ${b}${langn}/README.md${reset} for references, and more information. 
🐍
EndOfIntro
